### ISSUE TITLE
 Anonymous access 

### ISSUE THREAD

**Issue by 89z** [rapito/go-spotify#4]
You can make a request like this:

~~~
GET /playlist/6rZ28nCpmG5Wo1Ik64EoDm HTTP/1.1
Host: open.spotify.com
User-Agent: Firefox/60
~~~

and in part of the HTML response, you get this:

~~~json
{"clientId":"0971d",
"accessToken":"BQDLN9hyIJn0zvspT1OOHdJBQh7pJVrA1CMBMsuu3jOFDT6o37ti_pH8__M84opDUd0yqkzKxLIfjv9XmAw",
"accessTokenExpirationTimestampMs":1628533452806,"isAnonymous":true,
"recaptchaWebPlayerFraudSiteKey":"6LfCVLAUAAAAALFwwRnnCJ12DalriUGbj8FW_J39",
"app_name":"web_player_prototype","market":"US","locale":{"locale":"en","rtl":false,
"textDirection":"ltr"},"gtmId":"GTM-PZHN3VD","optimizeId":"GTM-W53X654","userCountry":null,
"isPremium":false,"correlationId":"f46dc1f60dc9e932d574104732a0173d",
"retargetingPixels":{"twitter":"o46zp","pinterest":"2617608197512",
"snapchat":"fff7f198-e6aa-4833-b900-92d3854473b2"}}
~~~

`accessToken` can then be used in a request like this:

~~~
GET /v1/playlists/6rZ28nCpmG5Wo1Ik64EoDm HTTP/1.1
Host: api.spotify.com
Authorization: Bearer BQDLN9hyIJn0zvspT1OOHdJBQh7pJVrA1CMBMsuu3jOFDT6o37ti_pH8__M84opDUd0yqkzKxLIfjv9XmAw
~~~

**Comment by rapito** [comment]
@89z can you clarify a bit more what the issue is? 
Im not sure I follow.

**Comment by 89z** [comment]
Currently this package requires any user to supply a `clientID` and `clientSecret`:

https://github.com/rapito/go-spotify/blob/8089a3ff31724ad1c678d2711b5567e70133bd63/spotify/spotify.go#L35-L38

as my comment above shows, this is not needed in all cases. Anonymous access could be added for limited actions, such as getting playlist information.

**Comment by rapito** [comment]
> Currently this package requires any user to supply a `clientID` and `clientSecret`:
> 
> https://github.com/rapito/go-spotify/blob/8089a3ff31724ad1c678d2711b5567e70133bd63/spotify/spotify.go#L35-L38
> 
> as my comment above shows, this is not needed in all cases. Anonymous access could be added for limited actions, such as getting playlist information.

Gotcha!

You can send over a PR and I'll be glad to review it and merge it. Thanks!

**Comment by 89z** [comment]
I dont be doing any PR. I will be making my own package. I just wanted to inform you and anyone visiting this page that anon access is possible. If you dont want to add thats your choice, but I think it would be a useful addition.

**Comment by rapito** [comment]
@89z 
That's alright, this is just an old test project it definitely should not be considered for production use. 
Thanks for bringing this up to my attention regardless. Good luck with your project!
